#!/bin/bash


if which -s phpcs; then
   alias phpcs="phpcs --standard=Drupal --report-width=`tput cols`"
   alias phpcs-all="phpcs --extensions=php,module,inc,install,test,profile,theme,js,css,info,txt"
fi
