#!/bin/bash


if which phpcs > /dev/null; then
   alias drupalcs="phpcs --standard=Drupal --report-width=`tput cols`"
   alias drupalcs-all="drupalcs --extensions=php,module,inc,install,test,profile,theme,js,css,info,txt"
fi
